spring:
  profiles.active: dev

  secuirt:
    basic.enable: false

  datasource:
    url: jdbc:h2:~/homs;MODE=MYSQL
    driverClassName: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
  h2:
    console.enabled: true

logging.level.org.springframework.security: INFO
