spring:
  profiles.active: dev

  secuirt:
    basic.enable: false

  datasource:
    url: jdbc:h2:~/homs;MODE=MYSQL
    driverClassName: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
  h2:
    console.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: homs.hyron@gmail.com
    password: hyron20170515
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
homs:
  rootUrl: http://localhost:8080

logging.level.org.springframework.security: INFO
